In [1]:
import torch
import torchvision
import numpy as np
import sys
sys.path.append("..") # 为了导入上层目录的d2lzh_pytorch
import d2lzh_pytorch as d2l
import importlib
importlib.reload(d2l)

<module 'd2lzh_pytorch' from '/media/wz209/a29353b7-1090-433f-b452-b4ce827adb17/xy/Dive-into-DL-PyTorch/mycode/d2lzh_pytorch/__init__.py'>

In [3]:
batch_size = 256
train_iter, test_iter = d2l.load_data_fashion_mnist(batch_size)

In [5]:
num_inputs = 784
num_outputs = 10

W = torch.tensor(np.random.normal(0, 0.01, (num_inputs, num_outputs)), dtype=torch.float)
b = torch.zeros(num_outputs, dtype=torch.float)

In [6]:
W.requires_grad_(requires_grad=True)
b.requires_grad_(requires_grad=True) 

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], requires_grad=True)

In [23]:
def softmax(X):
    X_exp = X.exp()
    X_sum = X_exp.sum(dim = 1, keepdim = True)
    out = X_exp / X_sum
    return out

In [26]:
X = torch.rand((2, 5))
print(X)
x_prob = softmax(X)

print(x_prob,  x_prob.sum(dim = 1))

tensor([[0.0336, 0.6809, 0.4445, 0.2214, 0.9233],
        [0.0632, 0.7975, 0.8984, 0.3303, 0.5582]])
tensor([[0.1241, 0.2370, 0.1871, 0.1497, 0.3021],
        [0.1200, 0.2500, 0.2766, 0.1567, 0.1968]]) tensor([1., 1.])


In [27]:
def net(X):
    return softmax(torch.mm(X.view((-1, num_inputs)),W) + b)